#!/bin/bash

# Path to secret files

PROFILE_NAME="$1"

for f in PROFILE_NAME; do
    if [[ -z "${!f}" ]]; then
        echo "Required argument missing: $f"
        exit 1
    fi
done

RESTIC_HTTP_CREDENTIALS="$(sudo cat /root/.restic_http_credentials_${PROFILE_NAME})"
source "/etc/restic-backup/${PROFILE_NAME}/backup.conf"

PASS="$(sudo cat /root/.restic_password_${PROFILE_NAME})"
CMD="${2-shell}"
INSTALL_PATH="/opt/restic-backup"
RCFILE_PATH="$INSTALL_PATH/restic_functions.sh"

case "$CMD" in
  shell)
    echo "Entering Restic environment..."
    echo "Repository: $(echo "$RESTIC_REPOSITORY" | sed -E 's#(https?://[^:@]+):[^@]+@#\1:*****@#')"
    env RESTIC_REPOSITORY="$RESTIC_REPOSITORY" RESTIC_PASSWORD="$PASS" bash --noprofile --rcfile $RCFILE_PATH -i
    echo "Exiting Restic environment."
    ;;

  mount)
    MNT_PATH="${3-/mnt/restic}"
    env RESTIC_REPOSITORY="$RESTIC_REPOSITORY" RESTIC_PASSWORD="$PASS" bash --noprofile -c "source $RCFILE_PATH; restic-mount $MNT_PATH"
    ;;

  snapshots)
    ARGS="${@:3}"
    env RESTIC_REPOSITORY="$RESTIC_REPOSITORY" RESTIC_PASSWORD="$PASS" bash --noprofile -c "source $RCFILE_PATH; restic-snapshots $ARGS"
    ;;

  *)
    echo "Usage: restic-env profile [shell|run <args>|prune]"
    exit 1
    ;;
esac
